module AbsMinSQL where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
newtype Str = Str String deriving (Eq,Ord,Show)
data Script =
   SStm [Command]
  deriving (Eq,Ord,Show)

data Command =
   CQuery Table
 | CInsert Ident VALUES
 | CUpdate Ident [Setting] WHERE
 | CDelete STAR Ident WHERE
 | CCreateDatabase Ident
 | CCreateTable Ident [Typing]
 | CAlterTable Ident Alter
 | CCreateView Ident Table
 | CCreateAssertion Ident Condition
 | CDescribe Ident
  deriving (Eq,Ord,Show)

data Query =
   QSelect TOP DISTINCT Columns Table WHERE GROUP HAVING ORDER
 | QSelectWith [Definition] Query
  deriving (Eq,Ord,Show)

data Columns =
   CCAll
 | CCExps [Exp]
  deriving (Eq,Ord,Show)

data WHERE =
   WNone
 | WCondition Condition
  deriving (Eq,Ord,Show)

data Table =
   TName Ident
 | TNameAlias Table Ident
 | TProduct Table Table
 | TUnion Table ALL Table
 | TIntersect Table ALL Table
 | TExcept Table ALL Table
 | TJoin Table Table ON
 | TNatJoin Table Table
 | TNatFullJoin Table Table
 | TLeftJoin Table Table ON
 | TRightJoin Table Table ON
 | TQuery Query
  deriving (Eq,Ord,Show)

data Exp =
   EName Ident
 | EQual Ident Ident
 | ENameAlias Exp Ident
 | EQuery Query
 | EInt Integer
 | EFloat Double
 | EStr Str
 | EString String
 | ENull
 | EList Exp [Exp]
 | EAggr AggrOper DISTINCT Exp
 | EAggrAll AggrOper DISTINCT
 | EDef
 | EAny Exp
 | EAll Exp
 | EMul Exp Exp
 | EDiv Exp Exp
 | EAdd Exp Exp
 | ESub Exp Exp
  deriving (Eq,Ord,Show)

data ON =
   OnNone
 | OnCondition Condition
 | OnUsing [Ident]
  deriving (Eq,Ord,Show)

data ALL =
   ANone
 | AAll
  deriving (Eq,Ord,Show)

data DISTINCT =
   DNone
 | DDISTINCT
  deriving (Eq,Ord,Show)

data TOP =
   TNone
 | TNumber Integer
 | TPercent Integer
  deriving (Eq,Ord,Show)

data GROUP =
   GNone
 | GGroupBy [Exp]
  deriving (Eq,Ord,Show)

data HAVING =
   HNone
 | HCondition Condition
  deriving (Eq,Ord,Show)

data ORDER =
   ONone
 | OOrderBy [Exp] DESC
  deriving (Eq,Ord,Show)

data DESC =
   DAsc
 | DDesc
  deriving (Eq,Ord,Show)

data VALUES =
   VColVal [Ident] [Exp]
 | VVal [Exp]
 | VTable Table
 | VColTable Ident [Ident] Table
  deriving (Eq,Ord,Show)

data Setting =
   SVal Ident Exp
  deriving (Eq,Ord,Show)

data STAR =
   StNone
 | StStar
  deriving (Eq,Ord,Show)

data AggrOper =
   AOMax
 | AOMin
 | AOAvg
 | AOCount
 | AOSum
  deriving (Eq,Ord,Show)

data Condition =
   COper Exp Oper Exp
 | CAnd Condition Condition
 | COr Condition Condition
 | CNot Condition
 | CExists Table
 | CIsNotNull Exp
 | CBetween Exp Exp Exp
 | CNotBetween Exp Exp Exp
 | CIn Exp VALUES
 | CNotIn Exp VALUES
  deriving (Eq,Ord,Show)

data Oper =
   OEq
 | ONeq
 | OGt
 | OLt
 | OGeq
 | OLeq
 | OLike
 | ONotLike
  deriving (Eq,Ord,Show)

data Typing =
   TColumn Ident Type [Constraint] DEFAULT
 | TConstraint Constraint [Ident]
 | TForeignKey Exp Ident [Ident] [Policy]
 | TReferences Ident Ident [Ident] [Policy]
 | TNamedConstraint Ident Constraint
  deriving (Eq,Ord,Show)

data Type =
   TIdent Ident
 | TSized Ident Integer
  deriving (Eq,Ord,Show)

data DEFAULT =
   DefNone
 | DefExp Exp
  deriving (Eq,Ord,Show)

data Constraint =
   CNotNull
 | CUnique
 | CPrimaryKey
 | CForeignKey Exp Ident [Ident] [Policy]
 | CReferences Ident [Ident] [Policy]
 | CCheck Condition
 | CNamed Ident Constraint
  deriving (Eq,Ord,Show)

data Policy =
   PDelete Action
 | PUpdate Action
  deriving (Eq,Ord,Show)

data Action =
   ACascade
 | ASetNull
  deriving (Eq,Ord,Show)

data Definition =
   DTable Ident Table Query
  deriving (Eq,Ord,Show)

data Alter =
   AAdd Typing
 | ADrop Ident
 | AAlter Ident Type
 | ADropPrimaryKey
 | ADropConstraint Ident
  deriving (Eq,Ord,Show)

