

module AbsXPath where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq,Ord,Show,Read)
data XPath =
   XPCont XAxis XItem XCond XPath
 | XPEnd
  deriving (Eq,Ord,Show,Read)

data XAxis =
   XAPlain
 | XADesc
  deriving (Eq,Ord,Show,Read)

data XItem =
   XINone
 | XIElem Ident
 | XIAttr Ident
 | XIAxis Ident Ident
 | XIAnces
  deriving (Eq,Ord,Show,Read)

data XCond =
   XCNone
 | XCOp XExp XOp XExp
  deriving (Eq,Ord,Show,Read)

data XExp =
   XEPath XPath
 | XEIdent Ident
 | XEAttr Ident
 | XEInt Integer
 | XEStr String
  deriving (Eq,Ord,Show,Read)

data XOp =
   XOEq
 | XONEq
  deriving (Eq,Ord,Show,Read)

