module AbsXPath where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data XPath =
   XPRoot XAxis XItem XCond
 | XPElem XPath XAxis XItem XCond
  deriving (Eq,Ord,Show)

data XAxis =
   XAPlain
 | XADesc
 | XAAnc
  deriving (Eq,Ord,Show)

data XItem =
   XINone
 | XIElem Ident
 | XIAttr Ident
  deriving (Eq,Ord,Show)

data XCond =
   XCNone
 | XCOp XExp XOp XExp
  deriving (Eq,Ord,Show)

data XExp =
   XEPath XPath
 | XEIdent Ident
 | XEAttr Ident
 | XEInt Integer
 | XEStr String
  deriving (Eq,Ord,Show)

data XOp =
   XOEq
 | XONEq
  deriving (Eq,Ord,Show)

