all: minsql algebra keywordalgebra xml executable

executable: 
	ghc --make -o qconv QConv.hs


minsql:
	bnfc -m --haskell MinSQL.bnf
	make
	cp -p Makefile.qconv Makefile

algebra:
	bnfc -m --haskell-gadt RelAlgebra.bnf
	make
	cp -p Makefile.qconv Makefile

keywordalgebra:
	bnfc -m --haskell KeywordRelAlgebra.bnf
	make
	cp -p Makefile.qconv Makefile

xml:
	bnfc -m --haskell-gadt XML.bnf
	make
	cp -p Makefile.qconv Makefile

