{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintRelAlgebra where

-- pretty-printer generated by the BNF converter

import AbsRelAlgebra
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))
  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])



instance Print Rels where
  prt i e = case e of
   RRels rels -> prPrec i 0 (concatD [prt 0 rels])


instance Print Rel where
  prt i e = case e of
   RTable id -> prPrec i 3 (concatD [prt 0 id])
   RSelect cond rel -> prPrec i 2 (concatD [doc (showString "\\sigma_{") , prt 0 cond , doc (showString "}") , prt 3 rel])
   RProject exps rel -> prPrec i 2 (concatD [doc (showString "\\pi_{") , prt 0 exps , doc (showString "}") , prt 3 rel])
   RRename renaming rel -> prPrec i 2 (concatD [doc (showString "\\rho_{") , prt 0 renaming , doc (showString "}") , prt 3 rel])
   RGroup ids aggregations rel -> prPrec i 2 (concatD [doc (showString "\\gamma_{") , prt 0 ids , prt 0 aggregations , doc (showString "}") , prt 3 rel])
   RSort ids rel -> prPrec i 2 (concatD [doc (showString "\\tau_{") , prt 0 ids , doc (showString "}") , prt 3 rel])
   RDistinct rel -> prPrec i 2 (concatD [doc (showString "\\delta") , prt 3 rel])
   RUnion rel0 rel -> prPrec i 1 (concatD [prt 1 rel0 , doc (showString "\\cup") , prt 2 rel])
   RJoin rel0 rel -> prPrec i 1 (concatD [prt 1 rel0 , doc (showString "\\bowtie") , prt 2 rel])
   RThetaJoin rel0 cond rel -> prPrec i 1 (concatD [prt 1 rel0 , doc (showString "\\bowtie_{") , prt 0 cond , doc (showString "}") , prt 2 rel])
   RIntersect rel0 rel -> prPrec i 1 (concatD [prt 1 rel0 , doc (showString "\\cap") , prt 2 rel])
   RCartesian rel0 rel -> prPrec i 1 (concatD [prt 1 rel0 , doc (showString "\\times") , prt 2 rel])
   RExcept rel0 rel -> prPrec i 1 (concatD [prt 1 rel0 , doc (showString "\\backslash") , prt 2 rel])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Cond where
  prt i e = case e of
   CEq exp0 exp -> prPrec i 2 (concatD [prt 0 exp0 , doc (showString "=") , prt 0 exp])
   CNEq exp0 exp -> prPrec i 2 (concatD [prt 0 exp0 , doc (showString "<>") , prt 0 exp])
   CLt exp0 exp -> prPrec i 2 (concatD [prt 0 exp0 , doc (showString "<") , prt 0 exp])
   CGt exp0 exp -> prPrec i 2 (concatD [prt 0 exp0 , doc (showString ">") , prt 0 exp])
   CLike exp0 exp -> prPrec i 2 (concatD [prt 0 exp0 , doc (showString "LIKE") , prt 0 exp])
   CNot cond -> prPrec i 2 (concatD [doc (showString "NOT") , prt 3 cond])
   CAnd cond0 cond -> prPrec i 1 (concatD [prt 1 cond0 , doc (showString "AND") , prt 2 cond])
   COr cond0 cond -> prPrec i 1 (concatD [prt 1 cond0 , doc (showString "OR") , prt 2 cond])


instance Print Exp where
  prt i e = case e of
   EIdent id -> prPrec i 3 (concatD [prt 0 id])
   EString str -> prPrec i 3 (concatD [prt 0 str])
   EInt n -> prPrec i 3 (concatD [prt 0 n])
   EFloat d -> prPrec i 3 (concatD [prt 0 d])
   EAggr function id -> prPrec i 3 (concatD [prt 0 function , doc (showString "(") , prt 0 id , doc (showString ")")])
   EMul exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "*") , prt 3 exp])
   EDiv exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "/") , prt 3 exp])
   EAdd exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "+") , prt 2 exp])
   ESub exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "-") , prt 2 exp])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Renaming where
  prt i e = case e of
   RRelation id -> prPrec i 0 (concatD [prt 0 id])
   RAttributes id ids -> prPrec i 0 (concatD [prt 0 id , doc (showString "(") , prt 0 ids , doc (showString ")")])
   RReplace id0 id -> prPrec i 0 (concatD [prt 0 id0 , doc (showString "/") , prt 0 id])


instance Print Aggregation where
  prt i e = case e of
   AgFun function id exp -> prPrec i 0 (concatD [prt 0 function , doc (showString "(") , prt 0 id , doc (showString ")") , doc (showString "\\rightarrow") , prt 0 exp])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Function where
  prt i e = case e of
   FAvg  -> prPrec i 0 (concatD [doc (showString "AVG")])
   FSum  -> prPrec i 0 (concatD [doc (showString "SUM")])
   FMax  -> prPrec i 0 (concatD [doc (showString "MAX")])
   FMin  -> prPrec i 0 (concatD [doc (showString "MIN")])
   FCount  -> prPrec i 0 (concatD [doc (showString "COUNT")])



