XPCont.  XPath ::= XAxis XItem XCond XPath ;
XPEnd.   XPath ::= ;

XAPlain. XAxis ::= "/" ;
XADesc.  XAxis ::= "//" ;

XINone.  XItem ::= ;
XIElem.  XItem ::= Ident ;
XIAttr.  XItem ::= "@" Ident ;
XIAxis.  XItem ::= Ident "::" Ident ;
XIAnces. XItem ::= ".." ;

XCNone.  XCond ::= ;
XCOp.    XCond ::= "[" XExp XOp XExp "]" ;

XEPath.  XExp  ::= XPath ;
XEIdent. XExp  ::= Ident ;
XEAttr.  XExp  ::= "@" Ident ;
XEInt.   XExp  ::= Integer ;
XEStr.   XExp  ::= String ;

XOEq.    XOp   ::= "=" ;
XONEq.   XOp   ::= "!=" ;


