XPRoot.  XPath ::= XAxis XItem XCond ;
XPElem.  XPath ::= XPath XAxis XItem XCond ;

XAPlain. XAxis ::= "/" ;
XADesc.  XAxis ::= "//" ;
XAAnc.   XAxis ::= "/.." ;
---XAIdent. XAxis ::= "/" Ident "::" ; ---- s-r conflict, overshadows XAPlain

XINone.  XItem ::= ;
XIElem.  XItem ::= Ident ;
XIAttr.  XItem ::= "@" Ident ;

XCNone.  XCond ::= ;
XCOp.    XCond ::= "[" XExp XOp XExp "]" ;

XEPath.  XExp  ::= XPath ;
XEIdent. XExp  ::= Ident ;
XEAttr.  XExp  ::= "@" Ident ;
XEInt.   XExp  ::= Integer ;
XEStr.   XExp  ::= String ;

XOEq.    XOp   ::= "=" ;
XONEq.   XOp   ::= "!=" ;


